spring:
  application:
    name: payment-service

  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/transactionDB
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create", otherwise use "update" to update the DB
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: manual_immediate
      retry:
        enabled: true
        max-attempts: 3
        error-handler:
          dead-letter-publish: true
      backoff:
        max-attempts: '3'
        multiplier: '2.0'
        max-interval: '10000'
        initial-interval: '1000'
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'


